apiVersion: v2
name: postgres-connector
description: Timescale Postgres connector — replicates Postgres into TimescaleDB.
type: application
version: 0.1.2
appVersion: ""
kubeVersion: ">=1.23.0-0"
home: https://github.com/timescale/postgres-connector-chart
sources:
  - https://github.com/timescale/live-sync
maintainers:
  - name: Timescale
    url: https://www.timescale.com
